[workspace]
members = [
	"typespace",
	"typespace-test-macro",
]

resolver = "2"

[workspace.dependencies]
codespace = "0.0.1-alpha.2"
expectorate = "1.2.0"
heck = "0.5.0"
json-serde = "0.0.1-alpha.3"
log = "0.4.29"
newline-converter = "0.3.0"
prettyplease = "0.3.0"
proc-macro2 = "1.0.104"
quote = "1.0.42"
regress = "0.12.0"
schemars = "0.8.22"
serde = "1.0.228"
serde_json = "1.0.148"
syn = { version = "3.0.3", features = ["full"] }
thiserror = "2.0.17"
trybuild = "1.0"
